### ISSUE TITLE
bug in interaction with canactivate function

### ISSUE THREAD

**Issue by dkostenko** [dagstuan/ng2-redux-router#3]
There is a problem with router function `canActivate`. If a guard returns `false`, router doesn't change current URI, but the ng2-redux-router changes the state of Router

Сode example below

Router with canActivate function:

```
const routes: RouterConfig = [
  {
    path: 'list',
    component: ListPage,
    canActivate: [LoggedInGuard]
  },
];
```

Guard with canActivate function implementation:

```
@Injectable()
export class LoggedInGuard implements CanActivate {
    constructor() {}
    canActivate(): boolean {
        return false;
    }
}
```

**Comment by dagstuan** [comment]
Thanks for the bug report. This issue should be fixed in 1.0.3, let me know if you're still having problems :)
